apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
  namespace: exercise
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
