apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercise
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        imagePullPolicy: Always
        image: arkuar/ping-pong:part4
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /healthz
            port: 3000
        resources:
          limits:
            cpu: "150m"
            memory: "100Mi"
        env:
          - name: DB_HOST
            value: postgredb-svc
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgredb-secret
                key: username
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgredb-secret
                key: database
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgredb-secret
                key: password
