apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-pong
          persistentVolumeClaim:
            claimName: log-claim
      containers:
      - name: ping-pong
        image: arkuar/ping-pong
        volumeMounts:
          - mountPath: /usr/src/app/files
            name: shared-pong
