apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercise
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: arkuar/ping-pong
