apiVersion: v1
kind: Service
metadata:
  name: postgredb-svc
  namespace: exercise
spec:
  selector:
    app: postgredb-app
  ports:
  - port: 5432
    name: web
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgredb-ss
  namespace: exercise
spec:
  selector:
    matchLabels:
      app: postgredb-app
  serviceName: postgredb-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: postgredb-app
    spec:
      containers:
      - name: postgredb
        imagePullPolicy: Always
        image: postgres:14.1
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgredb-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgredb-secret
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgredb-secret
                key: database
        ports:
        - containerPort: 5432
          name: web
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
