apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: exercise
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 3000
