apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml
- manifests/secret.yaml
- manifests/project-db.yaml
images:
- name: BACKEND
  newName: arkuar/todo-backend
  newTag: 10319f1eb34c16e4b197847444bcc25cafcc6f37
- name: FRONTEND
  newName: arkuar/todo-frontend
  newTag: 10319f1eb34c16e4b197847444bcc25cafcc6f37
