apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: todo-ns
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 10m
    successCondition: result < 2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1638-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(sum(rate(container_cpu_usage_seconds_total{namespace="todo-ns"}[10m])*100))