apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-todo
  namespace: todo-ns
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            image: arkuar/daily-todo:latest
            env:
              - name: URL
                value: http://web-server-svc:2346
          restartPolicy: OnFailure
