apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web-server
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
            - templateName: cpu-rate
  template:
    metadata:
      labels:
        app: web-server
    spec:
      volumes:
        - name: image-cache
          emptyDir: {}
      containers:
        - name: todo-backend
          image: arkuar/todo-backend:v2.0
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          volumeMounts:
            - mountPath: /usr/src/app/cache
              name: image-cache
          env:
            - name: REQUEST_ORIGIN
              value: http://web-server-svc
            - name: DB_HOST
              value: postgres-svc
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: NATS_URL
              value: nats://my-nats.default:4222
            - name: NATS_SUBJECT
              value: todos
          resources:
            limits:
              cpu: "150m"
              memory: "200Mi"
        - name: todo-frontend
          image: arkuar/todo-frontend:v1.9
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"