apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      volumes:
        - name: image-cache
          emptyDir: {}
      containers:
        - name: web-server
          image: arkuar/web-server:v0.6
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/src/app/cache
              name: image-cache