apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      volumes:
        - name: image-cache
          emptyDir: {}
      containers:
        - name: todo-backend
          image: arkuar/todo-backend:v1.3
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/src/app/cache
              name: image-cache
          env:
            - name: REQUEST_ORIGIN
              value: http://web-server-svc
            - name: DB_HOST
              value: postgres-svc
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
        - name: todo-frontend
          image: arkuar/todo-frontend:v1.2
          imagePullPolicy: Always