apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-hpa
  namespace: todo-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-server
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50