apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- project-db.yaml
images:
- name: BACKEND
  newName: arkuar/todo-backend
  newTag: 8980ef418c0696b52da50abd2232bed202deaf40
- name: FRONTEND
  newName: arkuar/todo-frontend
  newTag: 8980ef418c0696b52da50abd2232bed202deaf40
