name: Release /w GitOps

on:
  push:
    branches:
      - master
    paths:
      - 'project/backend/**'
      - 'project/frontend/**'
      - 'project/broadcaster/app/**'
      - '.github/workflows/release-gitops.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend
      uses: docker/build-push-action@v2
      with:
        context: project/backend
        push: true
        tags: arkuar/todo-backend:${{ github.sha }}
    - name: Build and Push Frontend
      uses: docker/build-push-action@v2
      with:
        context: project/frontend
        push: true
        tags: arkuar/todo-frontend:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Set up kustomize
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    # Update yamls
    - name: Update yamls
      working-directory: project
      run: |-
        kustomize edit set image FRONTEND=arkuar/todo-frontend:${{ github.sha }}
        kustomize edit set image BACKEND=arkuar/todo-backend:${{ github.sha }}

    # Commit and push 
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'project/kustomization.yaml'
        message: New version release for todo-project ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}